<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

$dependency = __DIR__ . '/node_modules/web-push/package.json';
if (!is_file($dependency)) {
    fwrite(STDERR, "Missing web-push dependency. Run npm ci --omit=dev first.\n");
    exit(1);
}
$node = getenv('BROWSER_PUSH_NODE_BINARY');
$node = is_string($node) && trim($node) !== '' ? trim($node) : 'node';
$process = proc_open([$node, __DIR__ . '/lib/generate-vapid.js'], [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes, __DIR__);
if (!is_resource($process)) {
    fwrite(STDERR, "Unable to start Node.js.\n");
    exit(1);
}
$output = stream_get_contents($pipes[1]);
$error = stream_get_contents($pipes[2]);
fclose($pipes[1]);
fclose($pipes[2]);
$exitCode = proc_close($process);
if ($exitCode !== 0) {
    fwrite(STDERR, trim((string)$error) . "\n");
    exit($exitCode);
}
$keys = json_decode((string)$output, true);
if (!is_array($keys) || !isset($keys['publicKey'], $keys['privateKey'])) {
    fwrite(STDERR, "web-push returned invalid key data.\n");
    exit(1);
}

fwrite(STDOUT, "VAPID keys generated by web-push. Store the private key in the CMS settings or environment, never under the public web root.\n\n");
fwrite(STDOUT, "BROWSER_PUSH_VAPID_PUBLIC_KEY=" . $keys['publicKey'] . "\n");
fwrite(STDOUT, "BROWSER_PUSH_VAPID_PRIVATE_KEY=" . $keys['privateKey'] . "\n");
fwrite(STDOUT, "BROWSER_PUSH_VAPID_SUBJECT=mailto:admin@example.com\n");
